spring:
    cloud:
        stream:
            bindings:
                input:
                    destination: test1
                    content-type: application/json
                    group: test_group
                myoutput1:
                    destination: test3
                    content-type: application/json
                output:
                    destination: test2
                    content-type: application/json
            kafka:
                binder:
                    autoAddPartitions: true
                    autoCreateTopics: true
                    brokers: 192.168.199.128:9092,192.168.199.128:9093,192.168.199.128:9094
                    minPartitionCount: 3
                    replication-factor: 1
                    configuration:
                        isolation.level: read_committed
                        security.protocol: SASL_SSL
                        sasl.mechanism: GSSAPI
                        sasl.kerberos.service.name: kafka
                        ssl.truststore.location: jks
                        ssl.truststore.password:
                        ssl.endpoint.identification.algorithm: null
                        auto-create-topics: false
                        transaction:
                            transaction-id-prefix: trans-2
                            producer:
                                configuration:
                                    retries: 2000
                                    acks: all
                                    security.protocol: SASL_SSL
                                    sasl.mechanism: GSSAPI
                                    sasl.kerberos.service.name: kafka
                                    ssl.truststore.location: jks
                                    ssl.truststore.password:
                                    ssl.endpoint.identification.algorithm: null
    kafka:
        consumer:
            auto-commit-interval: 1000ms
            auto-offset-reset: latest
            bootstrap-servers: 192.168.199.128:9092,192.168.199.128:9093,192.168.199.128:9094
            enable-auto-commit: false
            group-id: test-group
            max-poll-records: 10
            value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
        listener:
            ack-count: 10
            ack-mode: count_time
        producer:
            acks: 1
            batch-size: 1024000
            bootstrap-servers: 192.168.199.128:9092,192.168.199.128:9093,192.168.199.128:9094
            buffer-memory: 1024000
            properties:
                linger:
                    ms: 1000
            retries: 3
            value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer



##kafka-producer配置，官网=>https://kafka.apache.org/documentation/#producerconfigs
##集群地址
#    spring.kafka.producer.bootstrap-servers=192.168.199.128:9092,192.168.199.128:9093,192.168.199.128:9094
#  #指定创建信息nio-buffer缓冲区大小约1M
#    spring.kafka.producer.buffer-memory=1024000
#  #累计约1M条就发发送，必须小于缓冲区大小，否则报错无法分配内存（减少IO次数，过大则延时高，瞬间IO大）
#    spring.kafka.producer.batch-size=1024000
#  #默认0ms立即发送，不修改则上两条规则相当于无效（这个属性时个map列表，producer的其它配置也配置在这里，详细↑官网，这些配置会注入给KafkaProperties这个配置bean中，供#spring自动配置kafkaTemplate这个对象时使用）
#    spring.kafka.producer.properties.linger.ms=1000
#  #发送确认机制:acks=all或-1：leader会等待所有ISR中的follower同步完成的ack才commit(保证ISR副本都有数据leader才commit，吞吐率降低),acks=0：partition leader不会等待任何ISR中副本的commit（可能会有数据丢失，吞吐高），acks=1 kafka会把这条消息写到本地日志文件中
#    spring.kafka.producer.acks=1
#  #发送失败重试次数
#    spring.kafka.producer.retries=3
#  #kafkaTempalte默认的StringDeserializer序列化器（可指定json系列化器org.springframework.kafka.support.serializer.JsonSerializer，但同时消费的也要随着配置对应反序列化器org.springframework.kafka.support.serializer.JsonDeSerializer）
#    spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
#
#
#
#  #****************************************************************************
#  #kafka-consumer配置，官网=>https://kafka.apache.org/documentation/#producerconfigs
#    spring.kafka.consumer.bootstrap-servers=192.168.199.128:9092,192.168.199.128:9093,192.168.199.128:9094
#  #消费组ID
#    spring.kafka.consumer.group-id=test-group
#  #当未初始化消费组偏移量或没找到是怎么办？自动偏移量重置到最早的earlist（这个值会导致新加入的消费者去消费较久以前最开始的大量信息）,最新的latest（新消费者消费最新消息）,还是none或其它值报错
#    spring.kafka.consumer.auto-offset-reset=latest
#  #一次最大拉取多少条消息，太多处理消息压力大，太少则IO过于频繁；这个配置需要额外培养一个批量工厂bean，并在@KafkaListener注解指定这个批量工厂{@Link https://www.jianshu.com/p/5370fff55cff}
#    spring.kafka.consumer.max-poll-records=10
#  #自动提交consumer已消费的消息offset周期,周期过大，重启后可能重复消费较多已消费但offset未提交的消息,kafka scala程序有个定时任务来提交offset
#    spring.kafka.consumer.auto-commit-interval=1000ms
#  #仅在不开启上述周期性自动确认，配置其他的ack-mode才有效，如下累计10次消费才进行一次commit以修改消息消费者在该partition的offset
#    spring.kafka.consumer.enable-auto-commit=false
#  #计数模式，还是计时模式，手动ack模式等，配合ack-count一起配置
#    spring.kafka.listener.ack-mode=count_time
#    spring.kafka.listener.ack-count=10
#  #消费者的其它属性，类似producer，也是一个map
#  #spring.kafka.consumer.properties.XXX=YYY
#  #value即消息的反系列化方式，默认StringDeserializer
#    spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
#
#
#
#  #****************************************************************************
#  #springcloud-stream-kafka基本配置
#    spring.cloud.stream.kafka.binder.brokers=192.168.199.128:9092,192.168.199.128:9093,192.168.199.128:9094
#  #最小分区数
#    spring.cloud.stream.kafka.binder.minPartitionCount=3
#  #副本数
#    spring.cloud.stream.kafka.binder.replication-factor=1
#  #是否自动创建topic
#    spring.cloud.stream.kafka.binder.autoCreateTopics=true
#  #是否自动分区
#    spring.cloud.stream.kafka.binder.autoAddPartitions=true
#  #绑定消息发送通道到topic——test2
#    spring.cloud.stream.bindings.output.destination=test2
#  #绑定消息接收通道到topic——test1
#    spring.cloud.stream.bindings.input.destination=test1
#  #自定义消息发送通道myoutput1
#    spring.cloud.stream.bindings.myoutput1.destination=test2